name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pip
      run: sudo  pip install html5validator
    - name: Test html5
      run: html5validator --root _build/
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install surge
      run: npm install -g surge
    - name: Deploy to hoshiakise@gmail.com
      run: surge ./_build/ a-example.surge.sh --token ${{ secrets.SURGE_TOKEN }}   
